language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "11"
addons:
  postgresql: "9.3"

services:
  - postgresql

before_install:
  - npm install npm --global
env:
  - PGUSER=postgres PGDATABASE=postgres
